//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeBook.Resources.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستخدم.
        /// </summary>
        public static string lbActiveUser {
            get {
                return ResourceManager.GetString("lbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تغيير كلمة المرور .
        /// </summary>
        public static string lbbtnChangePassword {
            get {
                return ResourceManager.GetString("lbbtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح.
        /// </summary>
        public static string lbbtnDelete {
            get {
                return ResourceManager.GetString("lbbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbBtnEdit {
            get {
                return ResourceManager.GetString("lbBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ .
        /// </summary>
        public static string lbBtnSave {
            get {
                return ResourceManager.GetString("lbBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة مستخدم جديد.
        /// </summary>
        public static string lbBtnSaveNewRole {
            get {
                return ResourceManager.GetString("lbBtnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة مستخدم جديد.
        /// </summary>
        public static string lbBtnSaveNewUser {
            get {
                return ResourceManager.GetString("lbBtnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string lbCancelButtonText {
            get {
                return ResourceManager.GetString("lbCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم احذفها.
        /// </summary>
        public static string lbconfirmButtonText {
            get {
                return ResourceManager.GetString("lbconfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كتابة كلمة المرور.
        /// </summary>
        public static string lbConfirmpassword {
            get {
                return ResourceManager.GetString("lbConfirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة مستخدم جديد.
        /// </summary>
        public static string lbEditNewRole {
            get {
                return ResourceManager.GetString("lbEditNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string lbEmailUser {
            get {
                return ResourceManager.GetString("lbEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string lbEvents {
            get {
                return ResourceManager.GetString("lbEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string lbImageUser {
            get {
                return ResourceManager.GetString("lbImageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string lbManageBook {
            get {
                return ResourceManager.GetString("lbManageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لهذة الصفحة.
        /// </summary>
        public static string lbMsgDenied {
            get {
                return ResourceManager.GetString("lbMsgDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني او كلمة المرور غير صحيح.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغيير كلمة المرور.
        /// </summary>
        public static string lbMsgNotSaveChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSaveChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string lbMsgSaveChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSaveChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string lbNameRole {
            get {
                return ResourceManager.GetString("lbNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string lbNameUser {
            get {
                return ResourceManager.GetString("lbNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string lbNotSave {
            get {
                return ResourceManager.GetString("lbNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة المستخدم.
        /// </summary>
        public static string lbNotSaveMsgRole {
            get {
                return ResourceManager.GetString("lbNotSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        public static string lbOk {
            get {
                return ResourceManager.GetString("lbOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string lbRegisters {
            get {
                return ResourceManager.GetString("lbRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoles {
            get {
                return ResourceManager.GetString("lbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoleUser {
            get {
                return ResourceManager.GetString("lbRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مجموعة المستخدم -----.
        /// </summary>
        public static string lbSelectUserRole {
            get {
                return ResourceManager.GetString("lbSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;تم مسح مجموعة المستخدم بنجاح &apos;,.
        /// </summary>
        public static string lbTitleDeletedOk {
            get {
                return ResourceManager.GetString("lbTitleDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد ؟.
        /// </summary>
        public static string lbTitleDeleteMsg {
            get {
                return ResourceManager.GetString("lbTitleDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbTitleEdit {
            get {
                return ResourceManager.GetString("lbTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين الحاليين.
        /// </summary>
        public static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن تتمكن من التراجع !.
        /// </summary>
        public static string lmTextMsgDelete {
            get {
                return ResourceManager.GetString("lmTextMsgDelete", resourceCulture);
            }
        }
    }
}
